### ISSUE TITLE
Cannot start syncing with BSC mainnet

### ISSUE THREAD

**Issue by let4be** [streamingfast/firehose-ethereum#51] opened 2023-01-23 03:02 UTC
Firehose cannot start syncing spewing WARNs like this
```
WARN [01-23|07:00:25.852] Snapshot extension registration failed   peer=5a1afad4 err="peer connected on snap without compatible eth support"
WARN [01-23|07:00:26.322] Synchronisation failed, dropping peer    peer=ac4488f11a86a97c2c1331743f92339e9764681ae484e1a452aee69caef8a4b3 err=timeout
WARN [01-23|07:00:26.322] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [01-23|07:00:26.322] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
```

config:
```yaml
start:
  args:
  # Define Firehose components that will be used for this setup
  - merger
  - firehose
  - reader-node
  - relayer
  - combined-index-builder
  flags:
    # Prevent creation of file for logging (logs from previous sessions are not visible with this setting)
    log-to-file: true

    # Ethereum is the default chain, its id is 1. Update these flags for different chains such as Binance
    common-chain-id: "56"
    common-network-id: "56"
    # Update the reader-node-path to reference the geth binary for the chain and OS being targeted
    reader-node-path: ../geth/geth_linux
    # Update the reader-code-arguments for the chain being targeted
    # Find specific values in the Firehose Ethereum Setup Documentation
    reader-node-arguments: "+--maxpeers 500 --cache 4096 --snapshot=false --bootnodes=enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311,enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311,enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"
    reader-node-log-to-zap: false
    reader-node-bootstrap-data-url: ../geth/mainnet/genesis.json

    firehose-grpc-listen-addr: ":9000"
    substreams-enabled: true
    substreams-sub-request-parallel-jobs: 10
    substreams-partial-mode-enabled: true
    substreams-rpc-endpoints: "$BSC_SUBSTREAMS_RPC_ENDPOINT"
    substreams-sub-request-block-range-size: 100
    substreams-stores-save-interval: 100
```

**Comment by matthewdarwin** [comment] 2023-01-23 03:26
Which geth node are you running? https://github.com/streamingfast/go-ethereum/releases/tag/bsc-v1.1.18-fh2.1-2  ?

**Comment by let4be** [comment] 2023-01-23 03:44
```
./geth/geth_linux version
INFO [01-23|07:44:10.963] Initializing firehose 
INFO [01-23|07:44:10.966] Firehose initialized                     enabled=false sync_instrumentation_enabled=true mining_enabled=false block_progress_enabled=false compaction_disabled=false archive_blocks_to_keep=0 genesis_provenance="Geth Default" firehose_version=2.1 geth_version=1.1.18-fh2 chain_variant=bsc
Geth
Version: 1.1.18-fh2
Git Commit: 7d87cc8c32c5654fddbd4a20ff4cce6476b41ce2
Architecture: amd64
Go Version: go1.17.13
Operating System: linux
GOPATH=
GOROOT=go
```

**Comment by let4be** [comment] 2023-01-23 09:25
Now it syncs just fine. Probably some nodes were down and now are ok?

**Comment by maoueh** [comment] 2023-01-23 17:33
Yep, syncing a Geth node is often not easy and can take a long time just to start depending on network and network conditions. Closing as this is not a bug with firehose-ethereum.

**Closed by maoueh** 2023-01-23 17:33 UTC
